## AML

- **Name:** Hritik Vijay
- **Roll No.:** D21015

### Innovative points 

- **Section [ 1k ]**: In the Contend-Based Recommender Model, I tried to incorporate a model that, when given a movie name, would return a list of similar movies.
- **Section [ 2f ]**: Tried to incorporate string matching that would make it easier to call out movie with simple word or spelling and not necessarily exact word.

## Recommender System

Let's understand what is a Recommender System.

We have a seen the massive rise in the online-activity platforms. We as a customer/member of platforms like Amazon, Zomato, Netflix etc., are recommended a lot fo product, food or movies to watch. What we know is that, the kind of food recommended or the kind of movie are in someway close to our preferences. This in retun makes us use the platform more.

Taking the example of Netflix, we have a keen interest in different kind of genres. When we watch an action movie, we are then recommended other action movies. Likewise, in the case of any other genre. We can also notice that when we are a frequent watcher of an actor/actress, we are suggested more movies of the same actor. This is done by the model we will build today. 

Even in case of e-Commerce like Amazon Inc, keep advertising their products for us to purchase. This happens not only on their platform but are advertised on other platforms as well. But we need to understand why or how is this beneficial to us? 

A recommender system keeps advertising or suggesting its users to buy something. A user is usually interested in that and many end up buying it. The model checks for similarity in the kinds of things we buy and the different kinds of preference we have. Based on which, it looks for the same preference and choices in other items and recommends us. The more we are recommnded, more the chance for us to buy. This in exchange is profitable for the companies. This leads to advantages like:
- **Churn reduction**
- **Satisfaction of user**
- **Increased sales or conversions**

 The same goes for other sectors like Retail, Media, Entertainment, Banking and Telecom.

## 1. Content Based Filtering System

### 1a. ***Approach***

When we atch a movie, we do so based on certain attributes of the movie. There mainly are, whether we watch an action movie, or lets say we watch a particular actor a lot, or even any random movie which is new. These features of the kind of movies we watch can be stored in a vector and we can have multiple vectors for every movie. We know that a user will watch more movies if he/she has been recommended a movie that was similar to the type of movies that are watched. This is done by checking similarity between the vectors. Now, we know that we need to create pair wise similarity between movies, lets say based on their summary or the director of the movie or even the rating by the user. For this, we need to make vectors for each movie.

For example;

Lets take the help of the dataset:

In [1]:
import warnings
warnings.simplefilter("ignore")

In [2]:
import os
import pandas as pd
import numpy as np
os.chdir(r"/Users/hrit_vij/Desktop/Praxis/Term 2/AML/Recommendor System")

In [3]:
data = pd.read_csv("movies.csv")
data.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

we can see here that we have a set of genres for each movie. These are the content of the movie. Lets sat a particular user watches "Grumpier Old Men (1995)", then the user is likely. to be suggested a similar movie based on similar content like, "Waiting to Exhale(1995)" and then "Father of the Bride Part II (1995)". This is where similarity comes into the picture. 

The model here compares the vectors of every movie with one another to find similarities between movies, and based on which, it then recommends similar movies. In the above case, Comedy|Romance.

Here, we get cosine simiilaririty of the movies in the **not watched list** from the similarity matrix with respect of selected movie. More param√®tres can be added like, Actor, director etc,.

Although, we need to check that we do not over-specialise the model, i.e., two movies shouldn't be too similar as the user will then lose interest as he/she may have preffered it before. A good recommender system is such that it should provide the user with interested movies/shows that hasn't been seen before.

### 2. **User - User Collaborative Filtering**

- ***Approach***

Lets say there are two people **A** & **B** with similar activities. That also means they have similar likes for genres in the movie. Now both A and B might have watched similar movies. But there are high chances that A has watched a movie that B hasn't watched yet. Given the condition that A has liked the movie, we can say that B will also like the movie if recommended. 

We can do this using our model and check for the kind of movies A has watched and also check his reviews on different movies with the support that when its recommended to B, B will watch th movie. Every movie here will has a review or liking by the users. Basically, based on similarieties between A and B, the kind of movie we recomend one user will probably be liked by the other. Although, this involves predicting the rating for the movie watched. This is a basic idea of **User to User Collaborative Filtering**.

- This is done in the following steps:

1. Calculate similarty between the users.
2. This is followed by predicting rating of a movie not predicted yet by the user.
3. Then based on the similarity, it is recommended to the user. 

This helps us get an idea of the kind of movie a user will like and suggest a movie that hasn't been watched before.

In [4]:
ratings = pd.read_csv("ratings.csv")
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In simple laguage,

***Collaborative filtering is essentially a tool in order to find relationship between subsets subset of new users and the already existing users. This relationship is the similarity score between users.***

the User-to User Collaborative Filtering Model works on the ratings of a movie. It makes a cluster of likewise users with techniques like K-NN. The model then chceks for the ratings of the movies watched by the users in the cluster. When it finds that a movie is rated high by the these users and are yet to be watched by a few users, it then recommends these high rated movie to the users who hasn't watched it, with the prediction that it will be equally liked as the other users who has watched it.

====================================================================================================================================================================================================================================

====================================================================================================================================================================================================================================

# Building the Model

- the dataset : *movies.csv* , *ratings.csv*

  The dataset is a collection of 9742 movies with columns, id, title and genres and genres. Each movie is subjected to one or more genre and ratings.

1. **title**: The name of every movie with their year of release.
2. **genres**: The type of movie, whether *comedy, action or horror* or the combination of more than one.
3. **ratings**: The movies are given ratings by the users who have watched it.

# 1. Content Based Recommender System 

- *Approach*

**1. reading the data**

**2. Data Preparation**

**3. seeing similarities using cosine distance between the movies based on their genres.**

**4. making an matrix of similarity scores between movies. Higher the score, more similar the movie.**

**5. sorting the similarity score and finding the corresponding title.**

**6. selecting the top n movies as they are the most similar movies.**

**7. the model, when given a movie name as input, should return a list of similar movies as output.**

### 1a. Reading the data

In [5]:
## we start by importing necessary libraries
import os
import numpy as np
import pandas as pd

In [6]:
## readig the dataset
os.chdir(r"/Users/hrit_vij/Desktop/Praxis/Term 2/AML/Recommendor System")
data = pd.read_csv("movies.csv")
ratings = pd.read_csv("ratings.csv")

In [7]:
## for later modifications
data2 = data.copy()

In [8]:
## the first 5 rows
data.head(10)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller

In [9]:
## summary
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   object
 2   genres   9742 non-null   object
dtypes: int64(1), object(2)
memory usage: 228.5+ KB

### 1b. Data Preparations
We notice that every movie is associated with a year and this can totally be removed as its not really necessary and make the data more independent and not grouped on time.

In [10]:
## we extract the year part from the column title along with its brackets
## we then make this extracted year as a new column in the data
data['year'] = data.title.str.extract('(\(\d\d\d\d\))',expand=False)
data['year']

0       (1995)
1       (1995)
2       (1995)
3       (1995)
4       (1995)
         ...
9737    (2017)
9738    (2017)
9739    (2017)
9740    (2018)
9741    (1991)
Name: year, Length: 9742, dtype: object

In [11]:
## we then remove the brackets as its not really contributing to anything
data['year'] = data.year.str.extract('(\d\d\d\d)',expand=False)
data['year']

0       1995
1       1995
2       1995
3       1995
4       1995
        ...
9737    2017
9738    2017
9739    2017
9740    2018
9741    1991
Name: year, Length: 9742, dtype: object

In [12]:
## we then remove the year part from the title column
data['title'] = data.title.str.replace('(\(\d\d\d\d\))', '')
data['title']

0                                Toy Story
1                                  Jumanji
2                         Grumpier Old Men
3                        Waiting to Exhale
4              Father of the Bride Part II
                       ...
9737    Black Butler: Book of the Atlantic
9738                 No Game No Life: Zero
9739                                 Flint
9740          Bungo Stray Dogs: Dead Apple
9741          Andrew Dice Clay: Dice Rules
Name: title, Length: 9742, dtype: object

In [13]:
data.drop('year', axis='columns', inplace=True)

In [14]:
#Applying the strip function to get rid of any ending whitespace characters that may have appeared
data['title'] = data['title'].apply(lambda x: x.strip())

In [15]:
## the new dataset
data.head()

,movieId,title,genres
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji,Adventure|Children|Fantasy
2,3,Grumpier Old Men,Comedy|Romance
3,4,Waiting to Exhale,Comedy|Drama|Romance
4,5,Father of the Bride Part II,Comedy

### 1c. Data Interpretation

Since, we have multiple genres for a single movie, we cna make it more simple by doing one hot encoding for different movie genres.

In [16]:
data.head()

,movieId,title,genres
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji,Adventure|Children|Fantasy
2,3,Grumpier Old Men,Comedy|Romance
3,4,Waiting to Exhale,Comedy|Drama|Romance
4,5,Father of the Bride Part II,Comedy

In [17]:
## For example, let's see the number of movies for action genre
## show every row in which there is "Action" in the genre column
data.loc[(data.genres == "Action"),:].head()

     movieId                                              title  genres
8          9                                       Sudden Death  Action
63        71                                          Fair Game  Action
172      204                      Under Siege 2: Dark Territory  Action
215      251                                        Hunted, The  Action
555      667  Bloodsport 2 (a.k.a. Bloodsport II: The Next K...  Action

In [18]:
## the size of movies with action in genre column
data.loc[(data.genres == "Action"),:].shape

(60, 3)

There are 60 movies with Action in thrie genre.


### 1d. Genre List
##### Lets see the list of unique genres from every movie

Here, we make an empty list to store the unique genres. Now, we check that for every genre in the column genres, split the data on the basis of line (|). And then for all the single items after splitted, we check if a particular item is in the empty list or not. If not there, it is added or appends to the list and if present, it doesnt.

Hence, we get a list of all unique genres.

In [19]:
## Let us see the number of unique genres

## creating an empty list to store unique genres
genre_list = []

## for genres in coulms genres
for genre in data["genres"]:
    
    ## split the data between line
    genre_splitted = genre.split("|")
    
    ## for items in this split data
    for item in genre_splitted:
        
        ## if item is not in genre list, append to it
        if item not in genre_list:
            genre_list.append(item)

In [20]:
print("*****There are 20 different kinds of genre:*****\n",genre_list)

*****There are 20 different kinds of genre:*****
 ['Adventure', 'Animation', 'Children', 'Comedy', 'Fantasy', 'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror', 'Mystery', 'Sci-Fi', 'War', 'Musical', 'Documentary', 'IMAX', 'Western', 'Film-Noir', '(no genres listed)']

### Now, since we have so many genres and it becomes difficult to analyse which is which, we do a 1- Hot Encoding here for all the genres in the dataset.

### 1e. One - hot encoding

- **We know that for comparing the similarity using cosine similarity, we need to make the data more readable. This allows us to make the categorical data more expressive. This makes it more easy for the model to understand the data as it is now converted into a binary dataset.**

In [21]:
## for every genre in genre list
for genre in genre_list:
    ## setting the initial value as 0
    data[genre] = 0 #initial values set to zero

    ## iterating in all the rows
for index, row in data.iterrows():
    
    # for every genre present in genre list
    for present_genre in genre_list:
        
        ## if movie in rows, 
        if present_genre in row['genres']:
            
            ## set the value to 1
            data.loc[index, present_genre] = 1
            
        else:
            ## else set it to 0
            data.loc[index, present_genre] = 0

## We drop the columns movieId, title and genre
## we just consider the binary columns
movies_subset = data.iloc[:,3:]

- **We can now see the binary matrix**

In [22]:
movies_subset.head()

,Adventure,Animation,Children,Comedy,Fantasy,Romance,Drama,Action,Crime,Thriller,Horror,Mystery,Sci-Fi,War,Musical,Documentary,IMAX,Western,Film-Noir,(no genres listed)
0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

### 1f. Creating a Movie Movie Cosine Similarity

Now, since we need to compute the similarity between the vectors or in our case, movies, to select the most similar movies, we take this approach using Cosine Similarity Function. This in return gives us a score of the similarity that ranges between -1 to 1. 0 indicates a lack of similarity or correlation and 1 indicates the exact same vector. 

However, the algorithm performs cosine similarity computation between each possible pair of movies. If we have k movies, then we need to perform k-square computations.

Fortunately, we don't really need to compute it manually but rather can use a function from sklearn.metrics.pairwise

In [23]:
# !pip install sklearn

In [24]:
from sklearn.metrics.pairwise import cosine_similarity

In [25]:
## cosine similarity between vectors in movies_subset
cos_movies = pd.DataFrame(cosine_similarity(movies_subset))

In [26]:
cos_movie2 = cos_movies.copy()     # will be used later for modifications

In [27]:
## making titles as the rows and columns
cos_movies.index = data['title']
cos_movies.columns = data['title']
cos_movies

title,Toy Story,Jumanji,Grumpier Old Men,Waiting to Exhale,Father of the Bride Part II,Heat,Sabrina,Tom and Huck,Sudden Death,GoldenEye,...,Gintama: The Movie,anohana: The Flower We Saw That Day - The Movie,Silver Spoon,Love Live! The School Idol Movie,Jon Stewart Has Left the Building,Black Butler: Book of the Atlantic,No Game No Life: Zero,Flint,Bungo Stray Dogs: Dead Apple,Andrew Dice Clay: Dice Rules
title,,,,,,,,,,,,,,,,,,,,,
Toy Story,1.000000,0.774597,0.316228,0.258199,0.447214,0.000000,0.316228,0.632456,0.000000,0.258199,...,0.447214,0.316228,0.316228,0.447214,0.0,0.670820,0.774597,0.00000,0.316228,0.447214
Jumanji,0.774597,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.816497,0.000000,0.333333,...,0.000000,0.000000,0.000000,0.000000,0.0,0.288675,0.333333,0.00000,0.000000,0.000000
Grumpier Old Men,0.316228,0.000000,1.000000,0.816497,0.707107,0.000000,1.000000,0.000000,0.000000,0.000000,...,0.353553,0.000000,0.500000,0.000000,0.0,0.353553,0.408248,0.00000,0.000000,0.707107
Waiting to Exhale,0.258199,0.000000,0.816497,1.000000,0.577350,0.000000,0.816497,0.000000,0.000000,0.000000,...,0.288675,0.408248,0.816497,0.000000,0.0,0.288675,0.333333,0.57735,0.000000,0.577350
Father of the Bride Part II,0.447214,0.000000,0.707107,0.577350,1.000000,0.000000,0.707107,0.000000,0.000000,0.000000,...,0.500000,0.000000,0.707107,0.000000,0.0,0.500000,0.577350,0.00000,0.000000,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Black Butler: Book of the Atlantic,0.670820,0.288675,0.353553,0.288675,0.500000,0.288675,0.353553,0.000000,0.500000,0.288675,...,0.750000,0.353553,0.353553,0.500000,0.0,1.000000,0.866025,0.00000,0.707107,0.500000
No Game No Life: Zero,0.774597,0.333333,0.408248,0.333333,0.577350,0.000000,0.408248,0.000000,0.000000,0.000000,...,0.577350,0.408248,0.408248,0.577350,0.0,0.866025,1.000000,0.00000,0.408248,0.577350
Flint,0.000000,0.000000,0.000000,0.577350,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.707107,0.707107,0.000000,0.0,0.000000,0.000000,1.00000,0.000000,0.000000
Bungo Stray Dogs: Dead Apple,0.316228,0.000000,0.000000,0.000000,0.000000,0.408248,0.000000,0.000000,0.707107,0.408248,...,0.707107,0.500000,0.000000,0.707107,0.0,0.707107,0.408248,0.00000,1.000000,0.000000
Andrew Dice Clay: Dice Rules,0.447214,0.000000,0.707107,0.577350,1.000000,0.000000,0.707107,0.000000,0.000000,0.000000,...,0.500000,0.000000,0.707107,0.000000,0.0,0.500000,0.577350,0.00000,0.000000,1.000000

### 1g. Reference table

In [28]:
## making for our own reference to be used later
movie_list = data[["movieId","title"]]
movie_list.head()

   movieId                        title
0        1                    Toy Story
1        2                      Jumanji
2        3             Grumpier Old Men
3        4            Waiting to Exhale
4        5  Father of the Bride Part II

#### We are now done with our data preparation

###  Making the Recommender Model

### 1h. Finding top movies

We need to recommend only the top n number of movies and not all. For this we have made another function. 

We make a function top_movies with two objects, user_id and top_n. Lets say to consider a movie highly recommended, the ratings has to be good,i.e., the user's rating should match the top_n. So we first find the maximumrating that the user has given. We define a range and say if the max_rating by the person is less than that range, that means the user did not like any movie so far. 

Else, if the user has indeed liked a movie with higher ratings, then what we can do is define list of a 5-star and a 4-star rating movieId. This means that the user will like the 4 or 5-star rated movies.

We can do this usign various filters in the model like;
- if the number of 5-star rated movies are more than top_n number of movies, we randomly return a list of top_n movieId.
- ElseIf, the total numeber of 4 or 5-star rated movies are less than top_n, then we add all the 4 and 5 rated movies.
- otherwise, we return a list of all 5-rated movies and a few random selection from 4-rated movies.

In [29]:
def top_movies (user_id, top_n=5):
    
    ## making a threshold to like a movie based on rating
    max_rating = max(ratings.loc[(ratings.userId==user_id), "rating"])
    
    ## in our case, threshold rating is 4
    if max_rating < 4:
        print ("None liked so far!")
        return (None)
    
    
    else:
        
        ## condition for 5-rated movies
        movie_5 = ratings.loc[(ratings.userId==user_id)&(ratings.rating==5), "movieId"]
        
        ## condition for 4-rated movies
        movie_4 = ratings.loc[(ratings.userId==user_id)&(ratings.rating==4), "movieId"]
        
        ## If number of 5-rated movies are more than top_n, then return a List of randomly selected movie
        if len(movie_5) > top_n:
            return(list(np.random.choice(movie_5,5)))
        
        
        ## If the total number of 5-rated movies & 4-rated movies are less than top_n, then return a List
        elif len(movie_5) + len(movie_4) < top_n:
            return(list(movie_5)+list(movie_4))
        
        
        else:
            ## else return a list containing all the 5-rated movies and a few random selection from the 4 rated movies
            return(list(movie_5) + list(np.random.choice(movie_4, top_n-len(movie_5))))

In [30]:
top_movies(2)

[60756, 122882, 131724, 131724, 106782]

### 1i. Finding similar movies

Here, we make a function to get similar movies. Firstly, we give two objects, user_id and sim_score. Based on the user_id called, we get it corresponding title. Next, using the similarity matrix we found, we find the row where the title belongs. For which, we then find the scores of the movies that are similar. Now, since we have the movies with their similarity score, we check for all those movies whos similarity score is greater than our sim_value.


Hence, when we call the user_id and the range of similarity score, we get a list of similar movie.

**Keep in mind:** 

*A similarity score closer to 1 is more similar than the one away from it.*

In [31]:
def get_similar_movies (movie_id, sim=0.9):
    
    ## getting the title for the corresponding movie id
    title = movie_list.loc[movie_list.movieId==movie_id, "title"]
    title = np.array(title)[0]
    
   
    ## getting the row containing that movieID from the cosine similarity matrix
    similarity = cos_movies.loc[title,:]
    
    
    ## similarity scores of all movies
    scores = np.array(similarity)
    
    
    ## related movies that had similarity score of more than sim_value
    related = cos_movies.loc[title,: ][cos_movies.loc[title,:]>sim].index
    
    
    return(list(related))

In [32]:
get_similar_movies(2)

['Jumanji',
 'Indian in the Cupboard, The',
 'NeverEnding Story III, The',
 'Escape to Witch Mountain',
 "Darby O'Gill and the Little People",
 'Return to Oz',
 'NeverEnding Story, The',
 'NeverEnding Story II: The Next Chapter, The',
 'Santa Claus: The Movie',
 "Harry Potter and the Sorcerer's Stone (a.k.a. Harry Potter and the Philosopher's Stone)",
 'Chronicles of Narnia: The Lion, the Witch and the Wardrobe, The',
 'Bridge to Terabithia',
 'Golden Compass, The',
 'Water Horse: Legend of the Deep, The',
 'Chronicles of Narnia: Prince Caspian, The',
 'Alice in Wonderland',
 'Chronicles of Narnia: The Voyage of the Dawn Treader, The',
 'Percy Jackson: Sea of Monsters',
 'Seventh Son',
 'The Cave of the Golden Rose',
 'Pan',
 'Alice Through the Looking Glass',
 "Pete's Dragon",
 "Gulliver's Travels"]

# Recommendation System

 - **Since, we do not want the user to be recommended the movie alredy watched**
 
First, we get a list of movies user has watched based on the ratings he has given to movies he has watched. 

Then, we find the list of most similar watchlist for the user.

To get the movie he hasn't watched, we substract the movies_list with the movie watch. What remains is our **Recommended Movies**.

In [33]:
def user_watch_list (user_id):
    index = list(ratings.loc[ratings.userId==user_id, "movieId"].index)
    return(list(movie_list["title"][index]))

### 1j. Content Based Recommender System

In [34]:
N = 5                        # n number of top movies wanted
User = 10                    # Select the user id
top = top_movies(User, N)    # defining user_id and top_n
print(top)

[49272, 33794, 71579, 49286, 49272]

In [35]:
## to check which movie it corresponds to
movie_list.loc[movie_list.movieId==8869,:]

      movieId           title
5332     8869  First Daughter

In [36]:
## getting the most similar movie for the ith movie in the above List (LIST 1)
i = 1
sim_movies = get_similar_movies(top[i])
sim_movies

['Batman Begins']

In [37]:
## getting the watchlist of the user (LIST 2)
user_watch_list(User)

['Absolute Power',
 'That Darn Cat',
 "Vegas Vacation (National Lampoon's Las Vegas Vacation)",
 'Lost Highway',
 'Rosewood',
 'Donnie Brasco',
 'Booty Call',
 'Best Men',
 'Jungle2Jungle (a.k.a. Jungle 2 Jungle)',
 'Kama Sutra: A Tale of Love',
 'Private Parts',
 'Love Jones',
 'Saint, The',
 "Smilla's Sense of Snow",
 'Crash',
 'Daytrippers, The',
 'Liar Liar',
 'Selena',
 "Devil's Own, The",
 "Cats Don't Dance",
 'B*A*P*S',
 'Love and Other Catastrophes',
 'Turbo: A Power Rangers Movie',
 'Anna Karenina',
 'Double Team',
 'Inventing the Abbotts',
 'Anaconda',
 'Grosse Pointe Blank',
 'Kissed',
 '8 Heads in a Duffel Bag',
 'Paradise Road',
 "Romy and Michele's High School Reunion",
 'Temptress Moon (Feng Yue)',
 'Volcano',
 'Children of the Revolution',
 'Austin Powers: International Man of Mystery',
 'Breakdown',
 'Broken English',
 "Fathers' Day",
 'Fifth Element, The',
 'Nowhere',
 'Promise, The (La promesse)',
 'Shall We Dance? (Shall We Dansu?)',
 'Addicted to Love',
 'Brassed Off',
 'Lost World: Jurassic Park, The',
 'Ponette',
 'Schizopolis',
 'Shiloh',
 'Rough Magic',
 'Trial and Error',
 'Buddy',
 'Con Air',
 'Pillow Book, The',
 'Speed 2: Cruise Control',
 'Batman & Robin',
 "For Roseanna (Roseanna's Grave)",
 'Head Above Water',
 'Hercules',
 "My Best Friend's Wedding",
 "When the Cat's Away (Chacun cherche son chat)",
 'Contempt (M√©pris, Le)',
 'Face/Off',
 'Fall',
 'Men in Black (a.k.a. MIB)',
 'Out to Sea',
 'Wild America',
 'Simple Wish, A',
 'Contact',
 'Love Serenade',
 'G.I. Jane',
 'Conan the Barbarian',
 'George of the Jungle',
 'Cop Land',
 'Event Horizon',
 'Spawn',
 'Air Bud',
 'Picture Perfect',
 'In the Company of Men',
 'Career Girls',
 'Conspiracy Theory',
 'Desperate Measures',
 'Steel',
 "She's So Lovely",
 'Hoodlum',
 'Leave It to Beaver',
 'Mimic',
 'Money Talks',
 'Excess Baggage',
 'Kull the Conqueror',
 'Air Force One',
 '187 (One Eight Seven)',
 'Hunt for Red October, The',
 'My Own Private Idaho',
 'Kiss Me, Guido',
 'Star Maps',
 'In & Out',
 'Edge, The',
 'Peacemaker, The',
 'L.A. Confidential',
 'Seven Years in Tibet',
 'Kiss the Girls',
 'Soul Food',
 'Wishmaster',
 'Thousand Acres, A',
 'Game, The',
 'Fire Down Below',
 'U Turn',
 'MatchMaker, The',
 'Assignment, The',
 "Ulee's Gold",
 'Ice Storm, The',
 'Chasing Amy',
 'Full Monty, The',
 'Indian Summer (a.k.a. Alive & Kicking)',
 'Mrs. Brown (a.k.a. Her Majesty, Mrs. Brown)',
 'I Know What You Did Last Summer',
 "The Devil's Advocate",
 'RocketMan (a.k.a. Rocket Man)',
 'Playing God',
 'House of Yes, The',
 'Fast, Cheap & Out of Control',
 'Washington Square',
 'Year of the Horse',
 'Gattaca',
 'FairyTale: A True Story',
 'Phantoms',
 'Swept from the Sea',
 'Life Less Ordinary, A',
 'Hurricane Streets',
 "Eve's Bayou",
 'Switchback',
 'Gang Related',
 'Stripes',
 'Bean',
 'Mad City',
 'Welcome to Sarajevo',
 'Deceiver',
 'Rainmaker, The',
 'Boogie Nights']

In [38]:
## the movies in List A which are not in List B
## that is the movies in the similarity List which the user has not watched yet
not_watched = set(sim_movies)-set(user_watch_list(User))
not_watched

{'Batman Begins'}

In [39]:
## this is to check the common movies between the two
## that is removed from the list before recommdating the movies.
common_movies = set(user_watch_list(User)).intersection(set(sim_movies))
# common_movies

In [40]:
## length of similar movies
print(len(sim_movies))

## length of watched movie
print(len(user_watch_list(User)))

## length ov not watched movies
print(len(not_watched))

1
140
1

In [41]:
## the final list of new recommended movies for the user
not_watched = list(not_watched)
not_watched

['Batman Begins']

In [42]:
print('Searching for recommendations.....')

## get the scores of the movies in the not watched List from the similarity matrix WRT the selected movie
movie_name = np.array(movie_list.loc[movie_list.movieId==top[i],"title"])[0]
cos_movies.loc[movie_name, not_watched]

Searching for recommendations.....

title
Batman Begins    1.0
Name: Batman Begins, dtype: float64


### *(extra modifications)*
##  1k. Movies Recommendation Based on Movie Watched

### **Approach**

Here, I tried to make a model that will recommend a list of movies based on the title of the watched movie. 

Firstly, we index our "title" column so that it can be called/referred later. 

We know that the best recommended movie will be the one with the highest similarity or score. We make an empty list to store the recommended movie. What we do in this function is that we indexing to the title that is our object for the function. Now we know that we have our cosine similarity matrix. 

So, we give an index to the titles. This is done to call the title using the index. We now know that there is a similarity score for each movie. And for every title, we have an index. In return, we check the similarity score of that index (which is associated to a title) with all the other movies. Now, since we want top n numbers of movies recommended, we first convert it into a series and then sort the similarity scores and then select the top n numbers.

We know that for every score, there is a corresponding movie. Hence, we then append that movie to the empty list we have created earlier.

- **Note:** Here, we use the copy of matrix for cosine similarity which we had taken without alloting the column names and index. This because, as we need to make out title a series for this model, so that, a title associated with it can be call and compared for sim_score. Based on which we get our top_n movies for recommendation.

In [43]:
## indexing the movies in a series
# data2 = data.copy
index = pd.Series(data2['title'])
index.head()

0                      Toy Story (1995)
1                        Jumanji (1995)
2               Grumpier Old Men (1995)
3              Waiting to Exhale (1995)
4    Father of the Bride Part II (1995)
Name: title, dtype: object

In [44]:
def recommend_movies(title):
   
    ## making an empty list to store the similar movies
    movies = []
    
    ## making an index that corresponding the title to its index
    ## setting the initial index to 0
    idx = index[index == title].index[0]
    
    ## we can check the index by running the below staatement
#     print(idx)
    
    ## taking the score of similarity from the cosine matrix
    ## converting it into a series
    ## sorting the values in decending to choose the top n
    score = pd.Series(cos_movie2[idx]).sort_values(ascending=False)
    
    ## choosing the top 10 in this case 
    ## converting into a list of scores with an index
    top10 = list(score.iloc[:10].index)
    
      ## the top 10 movies in the list can be checked by running the beow code
#     print(top10)
    
    ## for every score in top10
    for i in top10:
        
        ## adding the corresponding title to the empty list movie we made earlier
        movies.append(data['title'][i])
    
    ## creating a dictory to store both id and the corresponding movie
    d = {"ids": top10,"title": movies}
    
    ## returning a table of recommended movies with their ids
    return pd.DataFrame(d)

In [45]:
recommend_movies("Iron Man (2008)")

    ids                               title
0   224  Star Wars: Episode IV - A New Hope
1  8694                      Thor: Ragnarok
2  8686             Avengers: Age of Ultron
3  8688                      Justice League
4  8689                             Ant-Man
5  7289                        Generation X
6  8458     Transformers: Age of Extinction
7  4619                 Returner (Ritaanaa)
8  8692                       Black Panther
9  8693     Avengers: Infinity War - Part I

====================================================================================================================================================================================================================================

====================================================================================================================================================================================================================================

====================================================================================================================================================================================================================================

====================================================================================================================================================================================================================================

# 2. Collaborative Filtering Based Recommendation Model

### ***Approach***

Unlike, Content Based Filtering, where we recommend a list of similar movies based on the features of the movie, say genre. In Collaborative filtering, we recommend a list based on liking of one user to another similar user.

Let's say we have multiple users and they have watched many movies. Now, if two people are similar , we can say that they will give similar rating to the same movie.In other words, like or dislike the movie. Lets say we have user A and user B. So we can make a list of movies watched and rated by user A , but not watched by user B, and send the list to user B to watch. On the support that, since user A is like user B or they are very similar, they would also like the similar rated movies.


Let us see how,

- *Approach*

**1. reading the data rating.csv, movies.csv**

**2. data prep - table rotation, standardisation** 

**3. make a table of movieId and userId based on ratings.**

**4. finding similarity using cosine similarity**

**5. using knn to find the nearest similar user**

**6. recommend a list of liked movie of one user to another user**

### 2a. Reading the data

In [46]:
## reading the movies dataset
movies = pd.read_csv(r"movies.csv")

## reading the ratings dataset
ratings = pd.read_csv(r"ratings.csv")

In [47]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [48]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

### 2b. Data Preparation

- **Here, we turn the table to make the rows as movieId and the columns as userId. This is done to make the data more easy to call as row wise.**

In [49]:
movies_users = ratings.pivot(index='movieId', columns='userId',values='rating')
movies_users

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
movieId,,,,,,,,,,,,,,,,,,,,,
1,4.0,NaN,NaN,NaN,4.0,NaN,4.5,NaN,NaN,NaN,...,4.0,NaN,4.0,3.0,4.0,2.5,4.0,2.5,3.0,5.0
2,NaN,NaN,NaN,NaN,NaN,4.0,NaN,4.0,NaN,NaN,...,NaN,4.0,NaN,5.0,3.5,NaN,NaN,2.0,NaN,NaN
3,4.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193585,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193587,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Centered Cosine

In a User-User Collaborative Filtering, we just do not do the centered cosine. But there is a way we do this. We first get the mean of all no-missing values in each row and then we replace each value in the row by the difference between the mean ans that value. We do this ofr all the rows.

This is followed by imputing 0 to all NaN values.

In [50]:
average = []
for i in range(0,len(movies_users)):
    mean = movies_users.iloc[i].mean()
    average.append(mean)
print(average)

[3.9209302325581397, 3.4318181818181817, 3.2596153846153846, 2.357142857142857, 3.0714285714285716, 3.946078431372549, 3.185185185185185, 2.875, 3.125, 3.496212121212121, 3.6714285714285713, 2.4210526315789473, 3.125, 3.8333333333333335, 3.0, 3.926829268292683, 3.7761194029850746, 3.7, 2.727272727272727, 2.5, 3.49438202247191, 3.2222222222222223, 3.125, 3.125, 3.625, 3.5, 3.3333333333333335, 4.2272727272727275, 4.0131578947368425, 3.0, 3.1842105263157894, 3.983050847457627, 3.65234375, 3.8358208955223883, 2.125, 3.293269230769231, 4.25, 3.7, 3.0, 3.1875, 2.5434782608695654, 3.3125, 3.066666666666667, 3.9753694581280787, 3.1470588235294117, 3.0, 4.237745098039215, 3.4642857142857144, 5.0, 2.3333333333333335, 4.0, 3.0625, 4.027027027027027, 3.235294117647059, 3.75, 3.70625, 2.7142857142857144, 2.2, 2.532258064516129, 2.5, 3.4, 3.775, 3.5090909090909093, 1.7, 3.2142857142857144, 3.4615384615384617, 4.0, 2.2, 3.4, 4.0, 3.3333333333333335, 2.764705882352941, 4.0, 3.107142857142857, 3.875, 3.0, 3.857142857142857, 3.966666666666667, 2.5, 3.15625, 3.25, 2.625, 2.8333333333333335, 3.95, 3.0238095238095237, 3.5, 3.9, 5.0, 2.7857142857142856, 3.782608695652174, 2.4, 3.0, 3.4393939393939394, 3.282608695652174, 4.0, 3.326923076923077, 4.0, 4.031645569620253, 4.105769230769231, 3.5434782608695654, 3.3333333333333335, 3.9, 3.0, 2.5, 3.0, 4.0, 2.65625, 4.375, 3.5833333333333335, 2.0, 3.0, 2.0, 2.8333333333333335, 2.9516129032258065, 3.0, 3.5, 3.494186046511628, 3.3333333333333335, 3.2450980392156863, 3.3333333333333335, 3.466666666666667, 5.0, 2.0, 3.845771144278607, 3.5454545454545454, 1.5, 2.9160583941605838, 3.875, 2.4166666666666665, 3.3333333333333335, 2.8636363636363638, 2.806451612903226, 2.892857142857143, 2.8771929824561404, 3.6359223300970873, 4.205882352941177, 3.5606060606060606, 3.3214285714285716, 3.5555555555555554, 2.8333333333333335, 3.0833333333333335, 2.4, 3.2285714285714286, 3.8333333333333335, 2.6792452830188678, 2.6693548387096775, 2.7, 3.975, 4.3076923076923075, 2.75, 1.0, 1.5, 3.4027777777777777, 2.264705882352941, 3.5, 3.5, 3.0401785714285716, 2.8229166666666665, 4.125, 3.4583333333333335, 3.0, 2.8, 2.4166666666666665, 2.4714285714285715, 3.6666666666666665, 3.1, 2.6666666666666665, 3.25, 4.125, 3.0, 3.0, 3.4318181818181817, 2.716666666666667, 3.1666666666666665, 3.0, 3.4285714285714284, 2.9130434782608696, 3.1666666666666665, 3.0, 3.5, 3.0, 3.8333333333333335, 4.0, 4.041666666666667, 3.326530612244898, 2.3333333333333335, 3.4285714285714284, 3.0, 3.0, 3.75, 3.855769230769231, 3.6125, 3.5384615384615383, 2.8636363636363638, 2.3333333333333335, 3.4285714285714284, 3.3958333333333335, 3.0601503759398496, 3.892857142857143, 3.5, 2.588235294117647, 3.6785714285714284, 3.477777777777778, 3.340909090909091, 4.0, 3.0, 2.375, 4.0, 3.6, 3.0, 4.293103448275862, 3.9285714285714284, 3.176470588235294, 3.7222222222222223, 2.5, 3.0, 3.453488372093023, 3.458715596330275, 3.0, 2.0714285714285716, 2.8285714285714287, 3.5, 2.6, 3.2, 4.231075697211155, 3.880952380952381, 3.9047619047619047, 4.0, 3.9393939393939394, 3.3970588235294117, 2.9411764705882355, 3.0, 3.4, 3.5, 3.7580645161290325, 2.9464285714285716, 2.9285714285714284, 2.0, 3.25, 3.223684210526316, 1.5, 3.0, 4.076923076923077, 3.7857142857142856, 3.3375, 3.6666666666666665, 4.5, 4.0, 3.0, 3.233695652173913, 3.5625, 4.035714285714286, 2.3333333333333335, 3.4257425742574257, 4.018796992481203, 3.0, 3.0, 4.197068403908795, 2.0, 4.0, 3.5185185185185186, 4.0, 3.2, 2.953125, 3.6666666666666665, 2.8333333333333335, 4.21875, 3.8958333333333335, 4.025, 3.0, 3.0, 1.4444444444444444, 3.3333333333333335, 3.75, 3.0789473684210527, 3.375, 3.2037037037037037, 4.429022082018927, 3.6, 3.0, 4.0, 3.55, 4.0, 2.5, 4.0, 2.823529411764706, 3.15, 3.3935185185185186, 3.0, 3.0, 2.8333333333333335, 3.78, 4.2, 3.5, 3.0, 3.7662337662337664, 2.8421052631578947, 3.4693877551020407, 3.4, 4.0, 3.272727272727273, 2.9, 3.040372670807453, 3.5972222222222223, 3.5, 3.5, 3.5833333333333335, 3.6045454545454545, 3.3859649122807016, 3.176470588235294, 2.5, 3.609375, 3.3333333333333335, 2.357142857142857, 4.164133738601824, 3.5194174757281553, 2.6666666666666665, 3.0, 2.6875, 3.0588235294117645, 3.5294117647058822, 4.0, 3.941860465116279, 3.25, 2.9166666666666665, 3.1847133757961785, 3.5, 4.0, 3.060344827586207, 3.3095238095238093, 2.761904761904762, 3.6363636363636362, 2.2, 3.25, 3.5292397660818713, 2.7857142857142856, 2.5, 3.497191011235955, 3.8181818181818183, 3.15625, 3.0952380952380953, 3.25, 4.0, 3.0, 2.375, 3.0, 4.5, 3.7, 4.5, 2.5, 2.4166666666666665, 3.0, 3.4375, 3.0, 2.0, 3.1011904761904763, 3.5, 2.7884615384615383, 2.3333333333333335, 2.53125, 2.5, 3.6923076923076925, 3.0, 2.675, 2.7203389830508473, 3.2083333333333335, 3.2, 2.85, 1.8333333333333333, 3.75, 3.142857142857143, 2.5416666666666665, 3.7222222222222223, 2.0, 3.75, 3.738095238095238, 2.6454545454545455, 2.75, 3.0346534653465347, 2.4206349206349205, 2.5714285714285716, 2.1666666666666665, 2.7142857142857144, 3.5460526315789473, 3.9285714285714284, 3.0925925925925926, 2.3333333333333335, 3.0, 3.8333333333333335, 3.625, 1.0, 3.0, 4.0, 3.0, 2.8, 3.5346534653465347, 2.391891891891892, 3.75, 3.9921052631578946, 2.8, 2.25, 2.6666666666666665, 2.75, 2.9, 2.8666666666666667, 5.0, 3.2045454545454546, 3.4, 1.0, 3.55, 2.5833333333333335, 1.8571428571428572, 3.692857142857143, 4.3, 1.0, 3.3823529411764706, 2.5, 2.25, 3.75, 3.1578947368421053, 3.625, 3.0, 2.9339622641509435, 3.0, 2.5, 3.0, 2.8636363636363638, 3.0, 3.2941176470588234, 3.75, 3.6666666666666665, 3.3780487804878048, 5.0, 5.0, 3.813953488372093, 2.5, 3.388888888888889, 3.6666666666666665, 2.3666666666666667, 3.0, 2.2142857142857144, 4.5, 3.3846153846153846, 3.6136363636363638, 3.540983606557377, 3.0, 3.0, 3.0, 3.375, 3.4166666666666665, 3.6041666666666665, 3.0555555555555554, 3.2777777777777777, 2.375, 2.4047619047619047, 3.130434782608696, 3.1666666666666665, 3.2857142857142856, 3.5, 3.485294117647059, 4.0, 4.225, 2.3333333333333335, 3.875, 3.25, 3.0, 2.888888888888889, 3.607142857142857, 3.2666666666666666, 3.3333333333333335, 3.1666666666666665, 3.5833333333333335, 3.4716981132075473, 2.6666666666666665, 4.100806451612903, 2.7857142857142856, 3.317073170731707, 2.4375, 2.0, 3.25, 2.75, 4.5, 3.4, 3.553763440860215, 3.262295081967213, 3.8153846153846156, 3.8, 3.3333333333333335, 2.9375, 3.5434782608695654, 4.0, 1.5, 2.0, 3.5, 2.6666666666666665, 3.5, 3.25, 2.65625, 2.125, 3.0, 2.8, 4.0, 4.0, 2.736111111111111, 2.9956896551724137, 3.4347826086956523, 3.7923497267759565, 3.970982142857143, 3.8353658536585367, 3.4285714285714284, 4.161290322580645, 3.616883116883117, 3.7705479452054793, 3.45, 3.4851851851851854, 3.8181818181818183, 4.0, 4.0, 3.0, 3.0, 4.116022099447513, 3.5714285714285716, 3.5454545454545454, 2.4166666666666665, 2.5, 3.1875, 3.0, 3.411111111111111, 2.8333333333333335, 3.0, 2.6, 5.0, 3.3333333333333335, 3.642857142857143, 3.1818181818181817, 4.0, 5.0, 2.25, 3.0, 3.0, 3.0454545454545454, 3.0, 3.0, 2.6818181818181817, 3.5, 3.3275862068965516, 3.537037037037037, 3.0, 3.0, 3.0923076923076924, 3.0, 3.4489795918367347, 3.2857142857142856, 3.2916666666666665, 4.333333333333333, 2.8125, 4.25, 4.75, 3.486111111111111, 2.707547169811321, 3.1666666666666665, 3.8333333333333335, 4.0, 4.125, 4.0, 2.3333333333333335, 3.3333333333333335, 2.0, 2.9545454545454546, 4.0, 2.7, 1.0, 3.2142857142857144, 2.0, 2.5714285714285716, 3.0, 2.880952380952381, 3.3879310344827585, 3.090909090909091, 2.5625, 3.05, 3.966666666666667, 3.6666666666666665, 4.125, 2.842857142857143, 4.092592592592593, 4.0, 3.032258064516129, 2.5, 3.0, 3.5, 3.3333333333333335, 3.6404958677685952, 3.9285714285714284, 3.321138211382114, 2.65, 4.148148148148148, 2.8181818181818183, 2.5172413793103448, 3.8958333333333335, 3.3333333333333335, 3.1136363636363638, 4.268041237113402, 4.0, 3.5, 4.25, 2.789473684210526, 2.4146341463414633, 3.5, 3.1578947368421053, 3.5, 3.5, 3.0, 4.03921568627451, 4.0, 3.4455445544554455, 3.5, 3.0, 3.3297872340425534, 2.8055555555555554, 3.369047619047619, 3.109375, 2.731707317073171, 2.0, 4.0, 3.5, 2.7083333333333335, 3.4565217391304346, 4.157894736842105, 3.1363636363636362, 3.3369565217391304, 4.0, 3.25, 3.657142857142857, 1.5, 3.5, 2.3333333333333335, 2.25, 2.8, 3.25, 3.5, 4.0, 3.3333333333333335, 2.6666666666666665, 3.0714285714285716, 3.3378378378378377, 2.0, 3.6666666666666665, 2.8823529411764706, 3.272727272727273, 3.9166666666666665, 2.8333333333333335, 3.375, 3.0, 2.5416666666666665, 3.2857142857142856, 2.9204545454545454, 2.8333333333333335, 3.1744186046511627, 4.2890625, 3.8333333333333335, 4.0, 1.75, 3.6666666666666665, 1.0, 3.5, 5.0, 3.0, 2.740740740740741, 2.1, 2.0, 2.5, 2.6666666666666665, 2.1666666666666665, 4.0, 3.8, 3.5384615384615383, 3.6666666666666665, 2.5, 3.75, 4.310344827586207, 4.074468085106383, 3.7083333333333335, 3.0, 3.8472222222222223, 4.025, 4.261904761904762, 4.321428571428571, 4.142857142857143, 3.5, 4.184210526315789, 3.962962962962963, 4.01, 3.8076923076923075, 4.24, 4.170454545454546, 4.042857142857143, 3.7666666666666666, 4.0576923076923075, 3.5, 4.1, 3.880434782608696, 3.6444444444444444, 3.388888888888889, 4.333333333333333, 4.043478260869565, 3.8944954128440368, 4.229166666666667, 4.0, 4.166666666666667, 3.5, 4.25, 3.8333333333333335, 3.9375, 4.217391304347826, 3.25, 3.8333333333333335, 4.0, 3.5, 3.25, 4.0, 3.75, 4.333333333333333, 3.9285714285714284, 4.0, 4.071428571428571, 2.5, 3.75, 3.9166666666666665, 3.9166666666666665, 3.857142857142857, 4.392857142857143, 3.625, 4.0344827586206895, 4.083333333333333, 3.861111111111111, 4.0, 3.5, 4.0, 3.0, 4.045454545454546, 3.75, 3.9705882352941178, 3.5, 4.1, 3.9, 3.0, 3.0, 3.0, 3.0, 3.5, 3.5384615384615383, 3.0, 3.0, 2.9, 3.3181818181818183, 3.0, 4.181818181818182, 2.5, 3.0, 3.0416666666666665, 2.5, 3.0, 2.1875, 3.5, 2.6, 3.0, 3.0555555555555554, 3.0555555555555554, 2.9375, 3.4444444444444446, 3.2083333333333335, 2.9, 2.95, 2.9, 3.5, 2.4166666666666665, 3.4705882352941178, 3.081081081081081, 2.3333333333333335, 3.488095238095238, 3.6153846153846154, 3.6666666666666665, 3.58, 3.017857142857143, 3.887323943661972, 3.3857142857142857, 2.7666666666666666, 3.4791666666666665, 3.375, 3.575, 3.1, 3.9375, 3.8620689655172415, 2.7708333333333335, 3.0, 4.590909090909091, 3.2738095238095237, 2.4, 4.5, 3.3181818181818183, 3.4761904761904763, 3.9, 4.0, 3.0, 2.0, 1.5, 3.0714285714285716, 3.466666666666667, 3.7222222222222223, 3.6944444444444446, 3.6724137931034484, 3.1538461538461537, 4.5, 3.5, 3.8739495798319328, 3.75, 3.409090909090909, 3.9225352112676055, 3.9269662921348316, 3.5416666666666665, 3.5833333333333335, 3.3333333333333335, 4.071428571428571, 3.5, 4.1, 3.369047619047619, 4.202290076335878, 3.984126984126984, 2.5476190476190474, 3.1914893617021276, 3.4054054054054053, 3.4404761904761907, 3.6666666666666665, 4.05, 3.7663934426229506, 3.375, 2.710526315789474, 3.3012048192771086, 4.1, 4.475, 4.666666666666667, 2.0, 4.125, 4.5, 3.0, 4.0, 3.5, 3.0, 3.537037037037037, 4.0, 4.25, 3.6538461538461537, 3.6875, 2.8333333333333335, 3.475806451612903, 2.5, 3.448717948717949, 2.9, 4.090909090909091, 4.0625, 3.1153846153846154, 4.161764705882353, 4.0, 5.0, 4.0, 3.9, 4.035714285714286, 4.333333333333333, 5.0, 3.5, 3.6666666666666665, 3.0, 1.0, 3.5, 2.5, 3.3529411764705883, 4.161764705882353, 3.1363636363636362, 3.8333333333333335, 4.0, 4.0, 4.541666666666667, 3.6296296296296298, 3.0, 3.7111111111111112, 3.9285714285714284, 3.95, 3.5869565217391304, 3.6, 3.659090909090909, 4.0, 3.1666666666666665, 3.5, 4.5, 4.203007518796992, 3.590909090909091, 4.2156398104265405, 4.232394366197183, 4.2075, 4.177966101694915, 3.9642857142857144, 4.145833333333333, 3.857142857142857, 4.149122807017544, 4.3, 3.995833333333333, 4.120689655172414, 4.219626168224299, 4.305555555555555, 4.137755102040816, 3.8846153846153846, 4.229166666666667, 4.25, 3.969178082191781, 4.03921568627451, 3.4545454545454546, 4.433333333333334, 4.0, 4.036144578313253, 3.8095238095238093, 4.25968992248062, 4.098039215686274, 4.089285714285714, 4.0, 4.184210526315789, 3.5, 4.0625, 4.1875, 3.8706896551724137, 3.8636363636363638, 3.625, 4.2125, 3.9765625, 4.288461538461538, 4.333333333333333, 4.222222222222222, 4.055555555555555, 3.8969465648854964, 4.05, 4.170731707317073, 3.96875, 4.106060606060606, 4.225, 3.9593023255813953, 4.063291139240507, 4.264705882352941, 4.071428571428571, 4.122222222222222, 4.071428571428571, 4.211864406779661, 3.82, 3.65625, 3.0, 3.8043478260869565, 3.685185185185185, 4.08256880733945, 4.0054945054945055, 3.7333333333333334, 4.044117647058823, 4.127906976744186, 3.8255813953488373, 3.8, 3.944055944055944, 4.111111111111111, 4.25, 3.611111111111111, 3.8793103448275863, 4.038011695906433, 3.5, 4.121212121212121, 4.045454545454546, 3.7435897435897436, 3.7291666666666665, 4.271929824561403, 4.125, 3.9927536231884058, 4.125, 4.333333333333333, 4.133333333333334, 3.7830188679245285, 4.2105263157894735, 4.142857142857143, 3.731707317073171, 3.0714285714285716, 3.9411764705882355, 4.015151515151516, 3.8636363636363638, 3.35, 4.046428571428572, 3.95, 3.8333333333333335, 3.227272727272727, 3.7058823529411766, 3.675, 3.760869565217391, 4.017857142857143, 4.166666666666667, 3.8076923076923075, 3.517857142857143, 4.029411764705882, 3.943548387096774, 3.5, 2.7, 3.8588235294117648, 5.0, 2.5, 2.0, 3.148936170212766, 3.4130434782608696, 1.5, 1.6666666666666667, 1.1666666666666667, 1.25, 1.125, 2.6333333333333333, 0.75, 2.75, 1.5, 2.0, 3.6666666666666665, 3.602272727272727, 3.0, 1.0, 1.0, 4.5, 3.4655172413793105, 3.1666666666666665, 3.75, 2.5, 3.78, 3.9642857142857144, 3.3472222222222223, 2.8125, 3.0, 3.53125, 5.0, 3.8181818181818183, 2.3333333333333335, 2.25, 3.375, 4.071428571428571, 2.0, 3.879120879120879, 4.0, 3.8404255319148937, 2.861111111111111, 4.083333333333333, 3.5, 3.5833333333333335, 3.9, 3.074468085106383, 3.4044117647058822, 3.0444444444444443, 3.3452380952380953, 2.6666666666666665, 3.7661290322580645, 3.261904761904762, 3.4767441860465116, 3.025, 3.1, 3.0, 3.139705882352941, 2.0789473684210527, 1.875, 2.8541666666666665, 4.0054945054945055, 2.6176470588235294, 1.4166666666666667, 2.6666666666666665, 3.0930232558139537, 4.125, 3.5941176470588236, 3.9913793103448274, 3.0, 3.4782608695652173, 4.0, 2.5, 3.1, 3.3333333333333335, 2.935483870967742, 4.5, 3.2, 3.8333333333333335, 2.5, 4.0, 3.5, 4.25, 3.0, 2.5, 3.4166666666666665, 3.25, 4.25, 2.75, 4.0, 3.0, 1.0, 1.0, 3.0, 3.575, 3.0, 2.46875, 2.7142857142857144, 4.25, 2.625, 2.1666666666666665, 1.5, 3.473684210526316, 3.5, 2.142857142857143, 4.428571428571429, 3.375, 3.875, 1.8333333333333333, 3.75, 2.0, 3.0833333333333335, 4.0, 2.6666666666666665, 3.25, 2.3125, 3.264705882352941, 3.3333333333333335, 3.7403846153846154, 2.6, 4.0, 2.1363636363636362, 4.0, 3.5384615384615383, 4.0, 3.216666666666667, 3.3636363636363638, 3.090909090909091, 3.6666666666666665, 3.0337837837837838, 3.0, 2.8333333333333335, 3.0, 1.5, 3.5, 2.0, 4.0, 4.0, 3.0, 1.9259259259259258, 3.610169491525424, 2.5, 3.0, 3.5, 2.9655172413793105, 3.0, 2.1, 3.0, 3.535, 3.3461538461538463, 1.0, 1.0, 3.7456896551724137, 3.3333333333333335, 4.5, 3.8076923076923075, 2.7, 3.7142857142857144, 2.753731343283582, 4.5, 3.5, 3.25, 4.0, 2.25, 2.1666666666666665, 3.0338983050847457, 2.4, 1.605263157894737, 2.2142857142857144, 4.0, 4.0, 3.4516129032258065, 3.5, 4.5, 3.0, 3.3701298701298703, 1.0, 3.487878787878788, 2.1666666666666665, 2.6, 3.0, 3.652439024390244, 3.0, 2.7954545454545454, 3.2580645161290325, 3.075, 3.28125, 2.94, 2.6346153846153846, 2.375, 2.8333333333333335, 4.083333333333333, 4.333333333333333, 2.941860465116279, 2.5, 2.3333333333333335, 3.5, 2.3333333333333335, 1.75, 2.4615384615384617, 3.3333333333333335, 2.75, 2.3333333333333335, 3.3448275862068964, 2.6666666666666665, 3.8722222222222222, 4.1, 3.0, 4.0, 2.7884615384615383, 3.0, 3.025, 4.061855670103093, 3.4285714285714284, 3.1153846153846154, 3.25, 2.25, 1.75, 3.7012987012987013, 2.6666666666666665, 3.357142857142857, 3.3333333333333335, 5.0, 4.0, 3.8823529411764706, 3.576923076923077, 3.7589285714285716, 1.75, 3.8, 2.109375, 3.411764705882353, 2.142857142857143, 2.5, 3.5, 2.5, 3.75, 4.5, 3.953488372093023, 3.5, 4.0, 4.0, 3.0625, 4.0, 3.0, 3.0, 3.0, 3.7941176470588234, 2.96875, 2.1, 3.0, 3.0, 3.375, 4.076923076923077, 3.65, 3.5, 3.33125, 2.0, 3.5, 2.0, 3.6, 1.9285714285714286, 3.812, 4.416666666666667, 3.5, 3.0, 3.6666666666666665, 3.2222222222222223, 3.35, 2.2142857142857144, 2.922222222222222, 3.5, 3.0, 4.0, 3.5, 4.0, 3.875, 3.0, 2.9, 4.078014184397163, 1.875, 3.1041666666666665, 3.0714285714285716, 2.9193548387096775, 3.25, 4.25, 3.414285714285714, 3.066666666666667, 2.6923076923076925, 3.75, 3.6979166666666665, 3.25, 1.75, 3.9245283018867925, 4.5, 4.055555555555555, 3.3181818181818183, 4.0, 2.0, 3.338709677419355, 3.8229166666666665, 2.5, 3.59375, 3.5, 4.1, 2.0, 5.0, 1.35, 2.3, 3.0, 2.9285714285714284, 2.5, 4.0, 2.7083333333333335, 3.419642857142857, 2.760869565217391, 2.8, 3.6979166666666665, 3.9, 2.3333333333333335, 3.0217391304347827, 4.0, 3.0, 4.25, 2.0, 3.423076923076923, 3.5, 3.0, 3.0161290322580645, 2.3125, 3.0, 4.0, 3.5, 3.6666666666666665, 2.0, 2.6666666666666665, 1.0, 3.5, 2.0, 3.3333333333333335, 3.25, 2.4482758620689653, 3.0, 4.0, 3.3823529411764706, 4.5, 2.25, 3.0, 3.2142857142857144, 3.0, 3.875, 3.966666666666667, 3.0416666666666665, 2.5714285714285716, 4.0, 3.5, 2.5625, 3.6666666666666665, 2.625, 1.9444444444444444, 2.4285714285714284, 2.9285714285714284, 2.0, 3.0, 3.75, 3.9166666666666665, 3.0697674418604652, 2.0, 1.9545454545454546, 3.2708333333333335, 3.967391304347826, 3.125, 2.0, 2.6666666666666665, 3.75, 2.0, 3.28125, 4.5, 2.84375, 3.3333333333333335, 3.5, 4.0, 4.0, 3.3333333333333335, 2.5, 3.566666666666667, 3.4404761904761907, 2.0, 2.609375, 3.859375, 4.0, 3.388888888888889, 3.4166666666666665, 3.0543478260869565, 2.8484848484848486, 2.5, 2.8333333333333335, 3.851063829787234, 3.5, 3.676190476190476, 3.1875, 3.0, 4.35, 3.5, 4.0, 4.166666666666667, 3.5, 3.0, 3.8333333333333335, 4.0, 3.25, 4.0, 4.0625, 4.0, 3.5, 4.25, 3.9545454545454546, 4.1875, 3.8333333333333335, 3.6029411764705883, 3.642857142857143, 4.333333333333333, 4.181818181818182, 3.5714285714285716, 3.9545454545454546, 3.871794871794872, 3.828125, 3.892857142857143, 4.0, 4.038461538461538, 3.7954545454545454, 3.6666666666666665, 3.6923076923076925, 3.8072916666666665, 3.739130434782609, 3.3636363636363638, 4.083333333333333, 3.380952380952381, 3.625, 3.8214285714285716, 3.7787610619469025, 2.35, 2.9166666666666665, 2.4285714285714284, 2.142857142857143, 2.2, 2.875, 2.5, 2.2142857142857144, 2.5833333333333335, 2.5, 3.25, 2.0, 2.0, 3.7222222222222223, 2.4, 2.1666666666666665, 2.0, 1.5, 2.5, 4.0, 2.7083333333333335, 2.375, 1.8, 3.425531914893617, 1.6666666666666667, 1.875, 3.80188679245283, 1.5, 2.0, 3.6733333333333333, 3.1808510638297873, 2.9347826086956523, 3.3780487804878048, 3.3333333333333335, 3.5701754385964914, 3.1, 3.5, 3.0, 3.473684210526316, 3.857142857142857, 3.5057471264367814, 3.3693181818181817, 3.0952380952380953, 2.625, 3.388888888888889, 2.875, 3.1, 3.3684210526315788, 4.1875, 4.0, 3.4324324324324325, 3.6875, 3.3555555555555556, 3.3333333333333335, 3.9285714285714284, 2.0, 1.8333333333333333, 4.1462765957446805, 2.0, 3.75, 2.611111111111111, 3.6666666666666665, 2.25, 4.0, 2.3333333333333335, 2.857142857142857, 3.3333333333333335, 2.5833333333333335, 2.75, 2.5, 3.2083333333333335, 3.5625, 2.875, 2.3333333333333335, 2.760869565217391, 2.05, 2.7573529411764706, 3.0, 3.0, 3.375, 3.35, 3.0, 3.0714285714285716, 3.838709677419355, 3.730769230769231, 4.125, 4.142857142857143, 2.75, 4.25, 3.4, 3.25, 3.176470588235294, 3.6, 3.6666666666666665, 5.0, 3.9456521739130435, 3.4, 3.830188679245283, 3.4, 3.425373134328358, 2.6538461538461537, 3.736842105263158, 2.7, 3.4318181818181817, 3.573170731707317, 2.5, 3.5, 3.1923076923076925, 2.25, 2.4166666666666665, 3.0, 3.2564102564102564, 2.8333333333333335, 3.409090909090909, 2.9, 2.5, 3.4166666666666665, 3.1176470588235294, 2.3333333333333335, 2.5, 4.0, 3.34, 3.7, 3.0, 3.4791666

In [51]:
for i in range(0,len(movies_users)):
    movies_users.iloc[i] = movies_users.iloc[i] - average[i]
movies_users

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
movieId,,,,,,,,,,,,,,,,,,,,,
1,0.079070,NaN,NaN,NaN,0.07907,NaN,0.57907,NaN,NaN,NaN,...,0.07907,NaN,0.07907,-0.920930,0.079070,-1.42093,0.07907,-1.420930,-0.92093,1.07907
2,NaN,NaN,NaN,NaN,NaN,0.568182,NaN,0.568182,NaN,NaN,...,NaN,0.568182,NaN,1.568182,0.068182,NaN,NaN,-1.431818,NaN,NaN
3,0.740385,NaN,NaN,NaN,NaN,1.740385,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.259615,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,0.642857,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,1.928571,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-0.071429,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193583,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193585,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193587,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- **fillig the nan values with 0**

In [52]:
user_subset = movies_users.fillna(0)

In [53]:
user_subset

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
movieId,,,,,,,,,,,,,,,,,,,,,
1,0.079070,0.0,0.0,0.0,0.07907,0.000000,0.57907,0.000000,0.0,0.0,...,0.07907,0.000000,0.07907,-0.920930,0.079070,-1.42093,0.07907,-1.420930,-0.92093,1.07907
2,0.000000,0.0,0.0,0.0,0.00000,0.568182,0.00000,0.568182,0.0,0.0,...,0.00000,0.568182,0.00000,1.568182,0.068182,0.00000,0.00000,-1.431818,0.00000,0.00000
3,0.740385,0.0,0.0,0.0,0.00000,1.740385,0.00000,0.000000,0.0,0.0,...,0.00000,0.000000,0.00000,0.000000,0.000000,0.00000,0.00000,-1.259615,0.00000,0.00000
4,0.000000,0.0,0.0,0.0,0.00000,0.642857,0.00000,0.000000,0.0,0.0,...,0.00000,0.000000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000,0.00000,0.00000
5,0.000000,0.0,0.0,0.0,0.00000,1.928571,0.00000,0.000000,0.0,0.0,...,0.00000,0.000000,0.00000,-0.071429,0.000000,0.00000,0.00000,0.000000,0.00000,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193581,0.000000,0.0,0.0,0.0,0.00000,0.000000,0.00000,0.000000,0.0,0.0,...,0.00000,0.000000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000,0.00000,0.00000
193583,0.000000,0.0,0.0,0.0,0.00000,0.000000,0.00000,0.000000,0.0,0.0,...,0.00000,0.000000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000,0.00000,0.00000
193585,0.000000,0.0,0.0,0.0,0.00000,0.000000,0.00000,0.000000,0.0,0.0,...,0.00000,0.000000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000,0.00000,0.00000
193587,0.000000,0.0,0.0,0.0,0.00000,0.000000,0.00000,0.000000,0.0,0.0,...,0.00000,0.000000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000,0.00000,0.00000
193609,0.000000,0.0,0.0,0.0,0.00000,0.000000,0.00000,0.000000,0.0,0.0,...,0.00000,0.000000,0.00000,0.000000,0.000000,0.00000,0.00000,0.000000,0.00000,0.00000

In [54]:
from sklearn import preprocessing
normalized = preprocessing.normalize(user_subset)

In [55]:
from sklearn.metrics.pairwise import cosine_similarity

## cosine similarity between vectors in movies_subset
cos_movies = pd.DataFrame(cosine_similarity(user_subset))

cos_movies

,0,1,2,3,4,5,6,7,8,9,...,9714,9715,9716,9717,9718,9719,9720,9721,9722,9723
0,1.000000,0.139649,0.113850,0.032658,0.076230,0.037291,0.064268,0.085986,0.041389,-0.008184,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.139649,1.000000,0.187303,-0.016897,0.154411,0.067458,0.067552,0.031078,0.046682,0.007021,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.113850,0.187303,1.000000,0.071153,0.220868,0.185618,0.195055,0.188311,0.160743,-0.010144,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.032658,-0.016897,0.071153,1.000000,0.128339,0.004044,0.022439,0.012922,0.000000,0.076458,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.076230,0.154411,0.220868,0.128339,1.000000,0.080362,0.217156,0.224129,0.070375,0.047833,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9719,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9720,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9721,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9722,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9723,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

- **standardizing**

In [56]:
# def standardize(row):
#     new_row = (row- row.mean())/(row.max()-row.min())
#     return new_row

# movie_users_std  = cos.apply(standardize)

# movie_users_std

### 2c. Data modification

- Since, the matrix is very large 9742x610, it requires a great computational effort. But, we see that  the matrix has a lot of 0 values, and so we can save a lot of computational effort by discarding the useless calculations.  So, we convert a dense matrix into a sparse matrix.

In [57]:
from scipy.sparse import csr_matrix

In [58]:
movies_users_mat=csr_matrix(cos_movies.values)

In [59]:
movies_users_mat

<9724x9724 sparse matrix of type '<class 'numpy.float64'>'
	with 17539616 stored elements in Compressed Sparse Row format>

### 2d. K - Neighrest Neighbours
Importing Nearest Neighbours library from sklearn

- now, we have a matrix of users and the movie they rated as userId and movieId resepectively. Now, since we know the values are basically ratings given by users for the corresponding movie. Hence, we can check the nearest neighbours that are likely to be similar to eachother, based on their ratings of a movie.

In [60]:
from sklearn.neighbors import NearestNeighbors

In [61]:
model_knn= NearestNeighbors(metric='cosine', n_neighbors=20)

- fitting the movie-user dataframe into the model the model

In [62]:
model_knn.fit(movies_users_mat)

NearestNeighbors(metric='cosine', n_neighbors=20)

In [63]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [64]:
## For our own refrence
ratings_list = ratings[["movieId","userId"]]
ratings_list.head()

   movieId  userId
0        1       1
1        3       1
2        6       1
3       47       1
4       50       1

In [65]:
## making for our own reference 
movie_list = data[["movieId","title"]]
movie_list.head()

   movieId                        title
0        1                    Toy Story
1        2                      Jumanji
2        3             Grumpier Old Men
3        4            Waiting to Exhale
4        5  Father of the Bride Part II

### 2e. Top Movies of an user

We first find the list of top movies for a user and on the basis of the movie, find similar movies.
- **We find the top movies of one user with userId, say: 59**

In [66]:
def top_movies (user_id, top_n=5):
    
    
    max_rating = max(ratings.loc[(ratings.userId==user_id), "rating"])
    if max_rating < 4:
        print ("None liked so far!")
        return (None)
    
    
    else:
        movie_5 = ratings.loc[(ratings.userId==user_id)&(ratings.rating==5), "movieId"]
        movie_4 = ratings.loc[(ratings.userId==user_id)&(ratings.rating==4), "movieId"]
        
        #If number of 5-rated movies are more than top_n, then return a List of randomly selected movie
        if len(movie_5) > top_n:
            return(list(np.random.choice(movie_5,5)))
        
        
        #If the total number of 5-rated movies & 4-rated movies are less than top_n, then return a List
        elif len(movie_5) + len(movie_4) < top_n:
            return(list (movie_5)+list (movie_4))
        
        
        #otherwise return a List containing all the 5-rated movies and a few random selection from the 4 rated movies
        else:
        
        
        
            return(list (movie_5) + list(np.random.choice(movie_4, top_n-len(movie_5))))

## 2f. Recommender Model


#### Creating Function

- ***Approach***


Creating a function with arguments as;
- **movie_name**: name of the movie rated
- **data**: data that is being used
- **model**: model we use, in our case, Nearest Neighours
- **n_recommendations**: number of recommendations we want to make


We first fit the data inside the knn model as we have to find the n neighbouring or similar users based on ratings. 

Now we need make a modificatio here by importing the fuzzywuzzy library. The lirary helps us to map similar strings. When given a query, it can be used to call a movie using, if not exact words, then similar words that matches the .We index the movies so that we can call out the movie with the help of an index. 

Now, we have ratings for every movie every user has watch. Using nearest neighbour, we find the similar users and then their top recommendation *(we know the similar users, so we can assume that if one user has liked a movie and rated it high, another similar user can watch that movie, if not watched)*.

For which , we calculate the distance of the neighbours to find similar users and then index their preference/recommendations. 

Finally we can run a for loop in the indices to get the list of top recommended movies that is called out by n_recommendations, in our case, top 10.

In [67]:
## importing library for extract a movie
from fuzzywuzzy import process

In [68]:
## function definition
def recommender(movie_name, data,model, n_recommendations ):
    ## fitting the data inside the model
    model.fit(data)
    
    ## indexing the movie in the dataset that match the movie_name
    ## 2 to choose the second column
    idx=process.extractOne(movie_name, movies['title'])[2]
        
    
    print('Searching for recommendations.....')
    
    ## calculating distance of similar movies using NN based on index of the movie extracted
    ## then the indexes of top rated movie's  are stored in indices
    distances, indices=model.kneighbors(data[idx], n_neighbors=n_recommendations)
    
    ## for every movie in indices
    for i in indices:
        
        ## printing the movie from the datset that corresponds to the index i
        ## but we avoid those movies which are same or have same index
        print(movies['title'][i].where(i!=idx))

In [69]:
recommender('space jam', movies_users_mat, model_knn,20)

Searching for recommendations.....
559                                                   NaN
302                     Ace Ventura: Pet Detective (1994)
1622                            Return to Paradise (1998)
645                                         Ransom (1996)
3057                                           Cop (1988)
95                          Muppet Treasure Island (1996)
5063                      Silence, The (Tystnaden) (1963)
2559                              Mo' Better Blues (1990)
1051                                 Crucible, The (1996)
133                                          Congo (1995)
1151                     Temptress Moon (Feng Yue) (1996)
1564                              Steamboat Willie (1928)
1336                           Fireworks (Hana-bi) (1997)
4108                                Brother (Brat) (1997)
475                                     Son in Law (1993)
2100    European Vacation (aka National Lampoon's Euro...
3428                                       Sweetie (1989)
1163                                   Brassed Off (1996)
3017                                    Claim, The (2000)
3388                               Johnny Handsome (1989)
Name: title, dtype: object

### 2g. Recommending 
- **We will take a random user and check his top 5 rated movies**

in our case user with user_id: 59

In [70]:
## the top 5 movies by user 59
top_movies(59)

[1269, 593, 1233, 1094, 2160]

### 2g.i
- **Now these are the top similar movies for user with userId: 59**
- **Let us check the similar users for a movie from the top movies with movie_id, say: 912**

In [71]:
## to check which other user has rated the same movie 
ratings_list.loc[ratings_list.movieId==912,:]

       movieId  userId
354        912       4
1123       912      10
1589       912      16
3802       912      23
4902       912      31
...        ...     ...
95239      912     600
95872      912     601
96291      912     603
97500      912     606
99590      912     610

[100 rows x 2 columns]

### 2g.ii
- **So, these are the users who has rated the same movie with movieId: 912**
- **From the table, let us find the top movies of another user with userId, say: 4**

In [72]:
## the top 5 movies by user 59
top_movies(4)

[260, 1283, 1197, 910, 920]

### 2g.iii
- **We now take one of these top_rated_movies of user with user id:4**
- **Check which movie it corresponds to.**
- **And then using our recommender function, find other similar rated movies to that movie**
- **That list of movies will be our recommendation for the first user**

In [79]:
## to check for one of these movies using the index and movie_list we made at the begining
movie_list.loc[movie_list.movieId==920,:]

     movieId               title
702      920  Gone with the Wind

### 2g.iv
- **Now these are the movie, the user has watched and rated.**
- **selecting one movie from here, we will check for similar movies.**

So, lets check for the movie, 'Gone with the Wind':

In [82]:
recommender('Gone with the Wind', movies_users_mat, model_knn,20)

Searching for recommendations.....
702                                                   NaN
926                                        Amadeus (1984)
1872                                       Payback (1999)
6274                                 Crime Busters (1977)
1533     Fanny and Alexander (Fanny och Alexander) (1982)
3967                                Monkey Trouble (1994)
4278                                 Sweet Charity (1969)
3109                               Of Mice and Men (1939)
3503                               Little Man Tate (1991)
2521                         Daughters of the Dust (1991)
1657                                  Secret Agent (1936)
6565                               No End in Sight (2007)
4059                                    Ghost Ship (2002)
3180                            Frankie and Johnny (1991)
2409                                      Papillon (1973)
3099                       3000 Miles to Graceland (2001)
3428                                       Sweetie (1989)
4744    Juliet of the Spirits (Giulietta degli spiriti...
1753      Nights of Cabiria (Notti di Cabiria, Le) (1957)
2890                 Original Kings of Comedy, The (2000)
Name: title, dtype: object

**Therefore, since the user has watched and rated "Gone with the Wind", the user can also watch the above list of movies.**

====================================================================================================================================================================================================================================

====================================================================================================================================================================================================================================